version: '3.1'

services:
    db:
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: example
            MYSQL_DATABASE: restphullp
    adminer:
        image: adminer
        ports:
            - 8080:8080
    web:
        build: .
        ports:
            - 80:80
        restart: always
        volumes:
            - ./code:/var/www/html
        depends_on:
            - db
