version: '3.1'

services:
    db:
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: presto
            MYSQL_USER: presto
            MYSQL_PASSWORD: presto
            MYSQL_DATABASE: presto
        volumes:
            - data:/var/lib/mysql
    adminer:
        image: adminer
        ports:
            - 8080:8080
    web:
        build: .
        ports:
            - 80:80
        restart: always
        volumes:
            - ../:/var/www/html
        depends_on:
            - db
volumes:
    data:
